'''


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

sumOfNums = 0
factor1 = 0
factor2 = 1
factor3 = 0

while factor1 < 4000000:
    factor3 = factor2
    factor2 = factor1 + factor2
    factor1 = factor3
    if factor2 % 2 == 0:
        sumOfNums += factor2
        if factor2 < 100000:
            print(factor2)
print(sumOfNums)

# a faster way to do this is to use the sum of even numbers in the Fibonacci sequence

